services:
  database:
    image: mysql
    container_name: nginx-proxy-manager-db
    hostname: nginx-proxy-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    restart: always
    networks:
      net:

  proxymanager:
    image: jc21/nginx-proxy-manager
    container_name: nginx-proxy-manager-app
    hostname: nginx-proxy-manager-app
    restart: unless-stopped
    environment:
      DB_MYSQL_HOST: database
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: root
      DB_MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
      DISABLE_IPV6: 'true'
    ports:
      - ${NPM_HTTP_PORT:-80}:80
      - ${NPM_HTTPS_PORT:-443}:443
      - ${NPM_ADMIN_PORT:-81}:81
    volumes:
      - data:/data
      - certs:/etc/letsencrypt
      - ./http.conf:/data/nginx/custom/server_proxy.conf:ro
    networks:
      net:
    depends_on:
      - database

volumes:
  data:
    name: nginx-proxy-manager-data
  certs:
    name: nginx-proxy-manager-certs
  database:
    name: nginx-proxy-manager-database

networks:
  net:
    external: false
