services:
  db:
    image: mysql
    container_name: proxy-db
    hostname: proxy-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks:
      - local

  proxymanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    restart: unless-stopped
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: root
      DB_MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
      DISABLE_IPV6: 'true'
    volumes:
      - data:/data
      - certs:/etc/letsencrypt
    networks:
      net:
        ipv4_address: ${APP_IP}
      local:
    dns:
      - ${DNS_IP_1}
      - ${DNS_IP_2:-9.9.9.9}
    depends_on:
      - db

  

volumes:
  data:
    name: nginx-proxy-manager-data
  certs:
    name: nginx-proxy-manager-certs
  db:
    name: nginx-proxy-manager-db

networks:
  net:
    external: true
    name: webapps-network
  local:
    driver: bridge
    internal: true
