services:
  proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '${ADMIN_WEBUI_PORT:-81}:81' # Admin Web Port
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: ${MYSQL_PORT:-3306}
      DB_MYSQL_USER: root
      DB_MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
      DISABLE_IPV6: 'true'
    volumes:
      - ${DATA_FOLDER:-./data}:/data
      - ${CERTS_FOLDER:-./certs}:/etc/letsencrypt
    networks:
      - net
    depends_on:
      - db

  db:
    image: 'mysql'
    container_name: proxy-db
    hostname: proxy-db
    environment:
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DB_FOLDER:-./mysql}:/var/lib/mysql
    restart: always
    networks:
      - net

networks:
  net:
    external: false
